// <auto-generated />
using System;
using CleanTeeth.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanTeeth.Persistence.Migrations
{
    [DbContext(typeof(CleanTeethDbContext))]
    [Migration("20260312212006_ChangeAddressType")]
    partial class ChangeAddressType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanTeeth.Domain.Entities.DentalOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OpeningDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DentalOffices");
                });

            modelBuilder.Entity("CleanTeeth.Domain.Entities.DentalOffice", b =>
                {
                    b.OwnsOne("CleanTeeth.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DentalOfficeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdditionalInfos")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Zipcode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DentalOfficeId");

                            b1.ToTable("DentalOffices");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("DentalOfficeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
